"""SPICE netlist generation from extracted parasitics.

This module provides utilities for generating SPICE netlists from
extracted RC/RLC networks, suitable for simulation with various
SPICE engines including jax-spice.
"""

from dataclasses import dataclass
from enum import Enum
from io import StringIO
from pathlib import Path

from jax_extract.extraction.network import RCNetwork


class NetlistFormat(str, Enum):
    """Supported SPICE netlist formats."""

    SPICE = "spice"
    """Standard SPICE format."""

    HSPICE = "hspice"
    """HSPICE-compatible format."""

    SPECTRE = "spectre"
    """Spectre-compatible format (Cadence)."""

    XYCE = "xyce"
    """Xyce-compatible format (Sandia)."""


@dataclass
class SimulationSetup:
    """Configuration for a SPICE simulation."""

    analysis_type: str = "tran"
    """Analysis type: tran, ac, dc, op."""

    t_stop: float = 100e-9
    """Stop time for transient analysis (seconds)."""

    t_step: float = 0.1e-9
    """Time step for transient analysis (seconds)."""

    f_start: float = 1e3
    """Start frequency for AC analysis (Hz)."""

    f_stop: float = 10e9
    """Stop frequency for AC analysis (Hz)."""

    points_per_decade: int = 10
    """Points per decade for AC analysis."""

    temperature: float = 27.0
    """Simulation temperature (Celsius)."""


@dataclass
class SimulationTestbench:
    """Configuration for a parasitic extraction testbench."""

    name: str
    """Testbench name."""

    dut_subckt: str
    """Name of the DUT subcircuit (extracted parasitics)."""

    input_node: str
    """Input node name."""

    output_node: str
    """Output node name."""

    vdd: float = 1.2
    """Supply voltage (V)."""

    input_rise_time: float = 100e-12
    """Input rise time (seconds)."""

    input_fall_time: float = 100e-12
    """Input fall time (seconds)."""

    load_capacitance: float = 0.0
    """Output load capacitance (Farads)."""

    driver_resistance: float = 0.0
    """Input driver resistance (Ohms)."""


class SpiceNetlistWriter:
    """Generate SPICE netlists from extracted RC networks.

    This class creates complete SPICE netlists including the extracted
    parasitics as a subcircuit, testbench, and analysis commands.

    Example:
        >>> writer = SpiceNetlistWriter()
        >>> netlist = writer.generate_subcircuit(rc_network)
        >>> print(netlist)
    """

    def __init__(self, format: NetlistFormat = NetlistFormat.SPICE):
        """Initialize netlist writer.

        Args:
            format: Target SPICE format.
        """
        self.format = format

    def generate_subcircuit(self, network: RCNetwork) -> str:
        """Generate a subcircuit from an RC network.

        Args:
            network: Extracted RC network.

        Returns:
            SPICE subcircuit definition as string.
        """
        return network.to_spice_subcircuit()

    def generate_testbench(
        self,
        network: RCNetwork,
        config: SimulationTestbench,
        setup: SimulationSetup | None = None,
    ) -> str:
        """Generate a complete testbench for RC network simulation.

        Args:
            network: Extracted RC network.
            config: Testbench configuration.
            setup: Simulation setup (uses defaults if None).

        Returns:
            Complete SPICE netlist as string.
        """
        if setup is None:
            setup = SimulationSetup()

        buf = StringIO()

        # Title
        buf.write(f"* Testbench: {config.name}\n")
        buf.write("* Generated by jax-extract\n")
        buf.write(f"* DUT: {config.dut_subckt}\n\n")

        # Options
        buf.write(f".TEMP {setup.temperature}\n")
        if self.format == NetlistFormat.HSPICE:
            buf.write(".OPTION POST ACCURATE\n")
        buf.write("\n")

        # Include the extracted subcircuit
        buf.write("* Extracted parasitics\n")
        buf.write(network.to_spice_subcircuit())
        buf.write("\n")

        # Instantiate DUT
        pins = network.get_pins()
        if len(pins) >= 2:
            pin_names = " ".join(p.spice_name for p in pins)
            buf.write("* DUT instance\n")
            buf.write(f"XDUT {pin_names} {network.name}_parasitic\n\n")

        # Voltage source for input stimulus
        buf.write("* Input stimulus\n")
        if setup.analysis_type == "tran":
            # PWL pulse for transient
            t_rise = config.input_rise_time
            t_fall = config.input_fall_time
            t_high = setup.t_stop / 4
            t_period = setup.t_stop / 2

            buf.write(f"VIN {config.input_node} 0 PWL(\n")
            buf.write("+  0 0\n")
            buf.write(f"+  {t_rise:.3e} {config.vdd}\n")
            buf.write(f"+  {t_high:.3e} {config.vdd}\n")
            buf.write(f"+  {t_high + t_fall:.3e} 0\n")
            buf.write(f"+  {t_period:.3e} 0\n")
            buf.write(f"+  {t_period + t_rise:.3e} {config.vdd}\n")
            buf.write(")\n\n")
        else:
            # DC source for AC/DC analysis
            buf.write(f"VIN {config.input_node} 0 DC {config.vdd} AC 1\n\n")

        # Driver resistance (optional)
        if config.driver_resistance > 0:
            buf.write("* Driver resistance\n")
            buf.write(f"RDRV in_drv {config.input_node} {config.driver_resistance}\n")
            buf.write("VIN_DRV in_drv 0 PWL(...)\n\n")

        # Load capacitance (optional)
        if config.load_capacitance > 0:
            cap_ff = config.load_capacitance * 1e15
            buf.write("* Load capacitance\n")
            buf.write(f"CLOAD {config.output_node} 0 {cap_ff:.3f}f\n\n")

        # Analysis commands
        buf.write("* Analysis\n")
        if setup.analysis_type == "tran":
            buf.write(f".TRAN {setup.t_step:.3e} {setup.t_stop:.3e}\n")
        elif setup.analysis_type == "ac":
            buf.write(
                f".AC DEC {setup.points_per_decade} {setup.f_start:.3e} {setup.f_stop:.3e}\n"
            )
        elif setup.analysis_type == "dc":
            buf.write(f".DC VIN 0 {config.vdd} {config.vdd / 100}\n")
        elif setup.analysis_type == "op":
            buf.write(".OP\n")

        # Output
        buf.write("\n* Output\n")
        if self.format == NetlistFormat.HSPICE:
            buf.write(f".PROBE V({config.input_node}) V({config.output_node})\n")
        else:
            buf.write(f".PRINT TRAN V({config.input_node}) V({config.output_node})\n")

        buf.write("\n.END\n")

        return buf.getvalue()

    def generate_rc_ladder_testbench(
        self,
        network: RCNetwork,
        setup: SimulationSetup | None = None,
    ) -> str:
        """Generate a testbench for measuring RC time constant.

        This creates a simple step-response testbench to measure
        the RC time constant of the extracted network.

        Args:
            network: Extracted RC network.
            setup: Simulation setup.

        Returns:
            SPICE netlist as string.
        """
        pins = network.get_pins()
        if len(pins) < 2:
            input_node = "in"
            output_node = "out"
        else:
            input_node = pins[0].spice_name
            output_node = pins[-1].spice_name

        config = SimulationTestbench(
            name=f"{network.name}_rc_test",
            dut_subckt=f"{network.name}_parasitic",
            input_node=input_node,
            output_node=output_node,
        )

        return self.generate_testbench(network, config, setup)

    def write_file(
        self,
        network: RCNetwork,
        output_path: Path,
        config: SimulationTestbench | None = None,
        setup: SimulationSetup | None = None,
    ) -> None:
        """Write netlist to file.

        Args:
            network: Extracted RC network.
            output_path: Output file path.
            config: Testbench configuration (subcircuit only if None).
            setup: Simulation setup.
        """
        if config is None:
            content = self.generate_subcircuit(network)
        else:
            content = self.generate_testbench(network, config, setup)

        output_path.write_text(content)


def rc_network_to_spice(network: RCNetwork) -> str:
    """Convenience function to convert RC network to SPICE.

    Args:
        network: Extracted RC network.

    Returns:
        SPICE subcircuit as string.
    """
    writer = SpiceNetlistWriter()
    return writer.generate_subcircuit(network)


def generate_step_response_testbench(
    network: RCNetwork,
    t_stop: float = 100e-9,
    vdd: float = 1.2,
) -> str:
    """Generate a step response testbench for RC measurement.

    Args:
        network: Extracted RC network.
        t_stop: Simulation stop time in seconds.
        vdd: Supply voltage.

    Returns:
        Complete SPICE netlist as string.
    """
    pins = network.get_pins()
    input_node = pins[0].spice_name if pins else "in"
    output_node = pins[-1].spice_name if len(pins) > 1 else "out"

    config = SimulationTestbench(
        name=f"{network.name}_step",
        dut_subckt=f"{network.name}_parasitic",
        input_node=input_node,
        output_node=output_node,
        vdd=vdd,
        input_rise_time=1e-12,  # Fast rise for step response
    )

    setup = SimulationSetup(
        analysis_type="tran",
        t_stop=t_stop,
        t_step=t_stop / 1000,
    )

    writer = SpiceNetlistWriter()
    return writer.generate_testbench(network, config, setup)
